# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'estDP_naked.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 420))
        MainWindow.setMaximumSize(QtCore.QSize(600, 420))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_file = QtWidgets.QMenu(self.menu)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.actionawawf = QtWidgets.QAction(MainWindow)
        self.actionawawf.setObjectName("actionawawf")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.save_prof_1 = QtWidgets.QAction(MainWindow)
        self.save_prof_1.setObjectName("save_prof_1")
        self.save_prof_2 = QtWidgets.QAction(MainWindow)
        self.save_prof_2.setObjectName("save_prof_2")
        self.save_prof_3 = QtWidgets.QAction(MainWindow)
        self.save_prof_3.setObjectName("save_prof_3")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu_file.addAction(self.save_prof_1)
        self.menu_file.addAction(self.save_prof_2)
        self.menu_file.addAction(self.save_prof_3)
        self.menu.addAction(self.menu_file.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_file.setTitle(_translate("MainWindow", "Записать данные в"))
        self.actionawawf.setText(_translate("MainWindow", "Первый пункт меню"))
        self.action_2.setText(_translate("MainWindow", "О программе"))
        self.save_prof_1.setText(_translate("MainWindow", "Профиль 1"))
        self.save_prof_2.setText(_translate("MainWindow", "Профиль 2"))
        self.save_prof_3.setText(_translate("MainWindow", "Профиль 3"))
        self.action_3.setText(_translate("MainWindow", "Выход"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
